<a href="https://colab.research.google.com/github/Marmalade17/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Assignment 3: Matrices


###Now that you have a basic understanding of Python, we'll try to explore into larger dimensions.

### Objectives
You will be able to do the following at the end of this activity:
1. Understand matrices and their relationship to linear equations.
2. Carry out basic matrix operations.
3. Python would be used to program and translate matrix equations and operations.

#Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

#Matrices

A Python matrix is a two-dimensional rectangular array of data with rows and columns. A matrix's data can be numbers, strings, equations, symbols, and so on. Matrix is a type of data structure that can be utilized in mathematical and scientific operations.

Let's say for example you have A and B as system of equation.



$$
A = \left\{
    \begin{array}\
        L + M \\ 
        4L - 10M
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        L+M+N \\ 
        3L -2M -N \\
        -L + 4M +2N
    \end{array}
\right. \\
C = \left\{
   \begin{array}\
        w-2x+3y-4z \\
        3w- x -2y +z \\
        2w -x + 3y - 2z
      \end{array}
\right. $$

We can see that A is a two-parameter system comprising two equations. whereas B is a system of three equations with three parameters. They can be represented as matrices as follows:

$$
A=\begin{bmatrix} 3 & 3 \\ 6 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 3 & 3 & 3 \\ 5 & -4 & -3 \\ -3 & 6 & 4\end{bmatrix}\\
C = \begin{bmatrix} 3& -4 & 5 & -6 \\ 5 & -3 & -4 & 3 \\ 4 & -3 & 5 & -4\end{bmatrix}
$$

Assuming you've already discussed the fundamental representation of matrices, as well as their kinds and operations. We'll do them in Python from here on out.

##Declaring Matrices

We'll represent a system of linear equations as a matrix, like we did in our previous laboratory exercise. The entities or numbers in matrices are referred to as matrix elements. These items are grouped and ordered in rows and columns, which create the matrix's list/array-like structure. And, like arrays, their elements are indexed based on their position in relation to their rows and columns.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We've already covered some of the many types of matrices as vectors, but we'll go over them again in this laboratory activity. We'll use the shape, dimension, and size attributes you already know how to describe vectors with to examine these matrices.

In [ ]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
L = np.array([
        [3, 4],
        [5, 3]
])
describe_mat(L)

Matrix:
[[3 4]
 [5 3]]

Shape:	(2, 2)
Rank:	2



In [ ]:
M = np.array([
    [14,18,15],
    [34,14,46]
])
describe_mat(M)


Matrix:
[[14 18 15]
 [34 14 46]]

Shape:	(2, 3)
Rank:	2



In [ ]:
## Declaring a 3 x 2.
N = np.array([
    [10, 4],
    [7, 6],
    [3, 3]
])
describe_mat(N)


Matrix:
[[10  4]
 [ 7  6]
 [ 3  3]]

Shape:	(3, 2)
Rank:	2



In [ ]:
O = np.array([1,2,3,4])
describe_mat(O)


Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1



##Categorizing Matrices

Matrixes can be classified in a variety of ways. One might be based on their shape, and the other on their element values. We'll make an effort to go through them.

###According to shape

####Row and Column Matrices

A row matrix is a 1-by-n (single row) matrix, whereas a column matrix is an n-by-1 matrix (a single column). Row and column matrices are sometimes known as row and column vectors.

In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
          3, 5, 4, -6
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row marix.
row_mat_2D = np.array([
          [3,4,5,-6]
]) ## This is a 2-D matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)

Matrix:
[ 3  5  4 -6]

Shape:	(4,)
Rank:	1

Matrix:
[[ 3  4  5 -6]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [3],
    [4],
    [7]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[3]
 [4]
 [7]]

Shape:	(3, 1)
Rank:	2



####Square Matrices

A square matrix is a matrix that has the same number of rows and columns. A square matrix of order is an n-by-n matrix. . Addition and multiplication can be performed on any two square matrices of the same order.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [3,4,7],
    [5,5,10],
    [8,3,4]
])

non_square_mat = np.array([
    [3,4,7],
    [5,5,10]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[ 3  4  7]
 [ 5  5 10]
 [ 8  3  4]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[ 3  4  7]
 [ 5  5 10]]

Shape:	(2, 3)
Rank:	2
Is Square: False



###According to element values

####Null Matrix

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [ ]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


####Zero Matrix

The zeros() function returns a new array of the specified shape and type, with the element's value set to 0.

In [ ]:
zero_mat_row = np.zeros((3,4))
zero_mat_sqr = np.zeros((4,4))
zero_mat_rct = np.zeros((5,4))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


####Ones Matrix

The Ones Matrix returns a new array of the specified shape and type, with the element's value set to 1.

In [ ]:
ones_mat_row = np.ones((3,4))
ones_mat_sqr = np.ones((4,4))
ones_mat_rct = np.ones((5,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


####Diagonal Matrix

A diagonal matrix is a matrix in linear algebra in which the entries outside the main diagonal are all zero; the word usually applies to square matrices.

In [ ]:
np.array([
    [4,0,0],
    [0,5,0],
    [0,0,7]
])
# a[3,3], a[2,2], a[4,4], ... a[n-1,n-1]

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

In [ ]:
d = np.diag([4, 5, 7, 9])
  #d.shape[0] == d.shape[1]
d

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])

####Identity Matrix

An Identity Matrix is a type of diagonal matrix in which the values on the diagonal are all ones.

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is one with a n value below the diagonal.

In [ ]:
np.array([
    [3,4,5,6],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])


array([[ 3,  4,  5,  6],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [ ]:
F = np.array([
              [4, -5, 6, -8, 7],
              [4, -5, 6, -8, 7],
              [4, -5, 6, -8, 7],
              [4, -5, 6, -8, 7],
              [4, -5, 6, -8, 7],
])
np.triu(F)


array([[ 4, -5,  6, -8,  7],
       [ 0, -5,  6, -8,  7],
       [ 0,  0,  6, -8,  7],
       [ 0,  0,  0, -8,  7],
       [ 0,  0,  0,  0,  7]])

####Lower Triangular Matrix

A Lower triangular matrix is one with a n value above the diagonal.

In [ ]:
np.tril(F)


array([[ 4,  0,  0,  0,  0],
       [ 4, -5,  0,  0,  0],
       [ 4, -5,  6,  0,  0],
       [ 4, -5,  6, -8,  0],
       [ 4, -5,  6, -8,  7]])

In [ ]:
np.array([
      [3,2,2],
      [7,5,2],
      [9,10,7]
])

array([[ 3,  2,  2],
       [ 7,  5,  2],
       [ 9, 10,  7]])

#Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 7x + 5y = z$$

2. Given the system of linear combination below, try to encode it as a matrix. Also decribe the matrix.

$$
A = \left\{\begin{array}
7x_3 + 4x_4 +x_5\\
6x_4 - x_5\\
13x_5
\end{array}\right.
$$

3. Given the matrix below, express it as a linear combination in a markdown and a laTeX Markdown.

In [32]:
G = np.array([
              [1,7,8],
              [2,2,2],
              [4,6,7]
])

Linear combination
$$
G = \left\{
    \begin{array}\
      x_1+7x_2+8x_3 \\
      2x_1+2x_2-2y_3 \\
      4x_1 + 6x_2 +7x_3
    \end{array}
\right.
$$

LaTex
$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}\\
$$

Linear combination
$$
H = \left\{
    \begin{array}\
      x_1\\
      2x_1+2x_2\\
      4x_1 + 6x_2 +7x_3
    \end{array}
\right.
$$

LaTex
$$
G=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}\\
$$

In [33]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

##Matrix Algebra

###Addition

In [24]:
X = np.array([
    [2,4],
    [4,6],
    [8,2]
])
Y = np.array([
    [4,4],
    [0,0],
    [3,3]
])
X+Y

array([[ 6,  8],
       [ 4,  6],
       [11,  5]])

In [ ]:
4+X ##Broadcasting
# 4*np.ones(A.shape)+A

array([[ 6,  8],
       [ 8, 10],
       [12,  6]])

###Subtraction

In [ ]:
X-Y

array([[-2,  0],
       [ 4,  6],
       [ 6,  0]])

In [ ]:
6-Y == 6*np.ones(Y.shape)-Y

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

###Element-wise Multiplication

In [ ]:
X*Y
np.multiply(X,Y)

array([[ 8, 16],
       [ 0,  0],
       [16,  4]])

In [ ]:
4*X

array([[ 8, 16],
       [16, 24],
       [32,  8]])

In [22]:
X@Y

array([[ 8,  8],
       [16, 16],
       [32, 32]])

In [ ]:
alpha=20**-20
X/(alpha+Y)

array([[5.000000e-01, 1.000000e+00],
       [4.194304e+26, 6.291456e+26],
       [4.000000e+00, 1.000000e+00]])

In [ ]:
np.add(X,Y)

array([[ 6,  8],
       [ 4,  6],
       [10,  4]])

#Activity

##Task 1

Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [12]:
## Function Area

import numpy as np




In [13]:
## Matrix Declarations

def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is a ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is a zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [14]:
## Sample Matrices
print('Matrix 1:')
mat_desc([[0,0,0,0], [0, 0, 0,0], [0,0,0,0]])
print('Matrix 2:')
mat_desc([[4, 3, 0, 1], [2, 6, 2,5], [7, 1, 2, 8]])
print('Matrix 3:')
mat_desc([[1, 3, 2, 2], [4, 7, 6, 2], [5, 6, 9, 4]])
print('Matrix 4:')
mat_desc([[1,1,1],[1,1,1],[1,1,1],[1,1,1], [1,1,1]])
print('Matrix 5:')
mat_desc([[7,1,5,0],[1,6,2,0],[4,8,6,9],[7,2,1,0],[1,9,1,5]])

Matrix 1:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape: (3, 4)
Size: 12
Rank: 0
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is a zeros matrix
Matrix 2:
[[4 3 0 1]
 [2 6 2 5]
 [7 1 2 8]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 3:
[[1 3 2 2]
 [4 7 6 2]
 [5 6 9 4]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 4:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (5, 3)
Size: 15
Rank: 1
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is a ones matrix
The matrix is not a zeros matrix
Matrix 5:
[[7 1 5 0]
 [1 6 2 0]
 [4 8 6 9]
 [7 2 1 0]
 [1 9 1 5]]
Shape: (5, 4)
Size: 20


##Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
3. 2. Returns the sum of the matrices.
4. Returns the differen of the matrices.
5. Returns the element-wise multiplication of the matrices.
6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
 import numpy as np

In [ ]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The matrices are not equal and invalid size operation.')
        return
    print('Sum of the  matrices:')
    matsum = mat1 + mat2
    print(matsum)
    print('Difference of the  matrices:')
    matdiff = mat1 - mat2
    print(matdiff)
    print('Element-wise multiplication of the  matrices:')
    matmul = np.multiply(mat1, mat2)
    print(matmul)
    print('Element-wise division of the  matrices:')
    matdiv = np.divide(mat1, mat2)
    print(matdiv)

In [ ]:
print('sample1:')
mat_operations([[2,3,2], [5,4,7], [4,3,8]], [[3,4,5],[9,7,1],[1,2,6]])
print('sample 2:')
mat_operations([[2, 6, 3,4], [3,3,1,5], [5,1,5,7]], [[3,7,5,7],[1,2,1,9],[1,1,1,6]])
print('sample 3:')
mat_operations([[2, 5, 1], [3,6,3], [6,1,5]], [[5,4,2],[3,4,6],[3,2,3]])
print('sample 4:')
mat_operations([[6,2,1,8,2], [3,6,3,7,8], [6,1,5,9,2]], [[5,4,2,7,7],[3,4,6,8,9],[3,2,3,6,2]])
print('sample 5:')
mat_operations([[6,2,1,8,2,5], [3,6,3,7,8,8], [6,1,5,9,2,2]], [[5,4,2,7,7,8],[3,4,6,8,9,2],[3,2,3,6,2,1]])

sample1:
Matrix 1: [[2 3 2]
 [5 4 7]
 [4 3 8]]
Matrix 2: [[3 4 5]
 [9 7 1]
 [1 2 6]]
Sum of the  matrices:
[[ 5  7  7]
 [14 11  8]
 [ 5  5 14]]
Difference of the  matrices:
[[-1 -1 -3]
 [-4 -3  6]
 [ 3  1  2]]
Element-wise multiplication of the  matrices:
[[ 6 12 10]
 [45 28  7]
 [ 4  6 48]]
Element-wise division of the  matrices:
[[0.66666667 0.75       0.4       ]
 [0.55555556 0.57142857 7.        ]
 [4.         1.5        1.33333333]]
sample 2:
Matrix 1: [[2 6 3 4]
 [3 3 1 5]
 [5 1 5 7]]
Matrix 2: [[3 7 5 7]
 [1 2 1 9]
 [1 1 1 6]]
Sum of the  matrices:
[[ 5 13  8 11]
 [ 4  5  2 14]
 [ 6  2  6 13]]
Difference of the  matrices:
[[-1 -1 -2 -3]
 [ 2  1  0 -4]
 [ 4  0  4  1]]
Element-wise multiplication of the  matrices:
[[ 6 42 15 28]
 [ 3  6  1 45]
 [ 5  1  5 42]]
Element-wise division of the  matrices:
[[0.66666667 0.85714286 0.6        0.57142857]
 [3.         1.5        1.         0.55555556]
 [5.         1.         5.         1.16666667]]
sample 3:
Matrix 1: [[2 5 1]
 [3 6 3]
 [6 1