<a href="https://colab.research.google.com/github/Marmalade17/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE


### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for matrix A, its transpose is denoted as  AT . So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$


$$B = \begin{bmatrix} 5 & -1 & 2\\0 & -3 &2 \\ 1 & 3 & -9\end{bmatrix} $$


$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

In [ ]:
X = np.array([
    [2 ,3, 6],
    [6, 0,1],
    [0, -3, 3]
])
X

array([[ 2,  3,  6],
       [ 6,  0,  1],
       [ 0, -3,  3]])

In [ ]:
XT1 = np.transpose(X)
XT1

array([[ 2,  6,  0],
       [ 3,  0, -3],
       [ 6,  1,  3]])

In [ ]:
XT2 = X.T
XT2

array([[ 2,  6,  0],
       [ 3,  0, -3],
       [ 6,  1,  3]])

In [ ]:
np.array_equiv(XT1, XT2)

True

In [ ]:
Y = np.array([
    [1,5,7,4],
    [2,0,2,0],
    [1,5,7,4],
    [2,0,2,0],
])
Y.shape

(4, 4)

In [ ]:
np.transpose(Y).shape

(4, 4)

In [ ]:
Y.T.shape

(4, 4)

Try to create your own matrix (you can try non-squares) to test transposition

In [ ]:
Josa= np.array ([
    [6, 5, 1],
    [1, -4, 8],
    [2, 5, 7],
    [3,80,97]
])
print('Josa matrix: \n',Josa, '\n')
print('Shape: ',Josa.shape)


Josa matrix: 
 [[ 6  5  1]
 [ 1 -4  8]
 [ 2  5  7]
 [ 3 80 97]] 

Shape:  (4, 3)


In [ ]:
print('Transpose Shape: ',np.transpose(Josa).shape)

Transpose Shape:  (3, 4)


In [ ]:
print('Transpose Shape: ',Josa.T.shape)

Transpose Shape:  (3, 4)


## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
L = np.array([
    [2,3],
    [-1,0]
])
M = np.array([
    [-2,-1, 0],
    [3,3, 3]
])

In [ ]:
N= np.array ([  
    [1,7,8,9,5,6,0],
    [2,5,6,7,8,9,1]
])

In [ ]:
np.array_equiv(L,M)

False

In [ ]:
np.dot(L,M)

array([[5, 7, 9],
       [2, 1, 0]])

In [ ]:
L.dot(M)

array([[5, 7, 9],
       [2, 1, 0]])

In [ ]:
L @ M

array([[5, 7, 9],
       [2, 1, 0]])

In [ ]:
np.matmul(L,M)

array([[5, 7, 9],
       [2, 1, 0]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
X = np.array([
    [3, 5],
    [4, -3],
    [1, 2]
])
Y = np.array([
    [2,2],
    [4,4],
    [-2,-3]
])
Z = np.array([
    [1,2,2],
    [0,0,3]
])
print(X.shape)
print(Y.shape)
print(Z.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
X @ Z

array([[ 3,  6, 21],
       [ 4,  8, -1],
       [ 1,  2,  8]])

In [ ]:
Y @ Z

array([[  2,   4,  10],
       [  4,   8,  20],
       [ -2,  -4, -13]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
X @ Y.T

array([[ 16,  32, -21],
       [  2,   4,   1],
       [  6,  12,  -8]])

In [ ]:
L = np.array([
    [1,-2,4, 5],
    [2,-3,4,-5]
])
M = np.array([
    [0,-1,3, 4],
    [4,-2,5,-4]
])
print(L.shape)
print(M.shape)

(2, 4)
(2, 4)


In [ ]:
M.T @ L

array([[  8, -12,  16, -20],
       [ -5,   8, -12,   5],
       [ 13, -21,  32, -10],
       [ -4,   4,   0,  40]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
J = np.array([
    [7, 5,3],
    [3, 4,7],
    [5, 7,1]
])
O = np.array([
    [8,3,8],
    [5,6,9],
    [7,2,5]
])
N = np.array([
    [1,5,2],
    [2,6,8],
    [6,3,7]
])

In [ ]:
J.dot(np.zeros(J.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(J.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
j_dot_z = J.dot(np.zeros(J.shape))
j_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(j_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(J.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(j_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
X = np.array([
    [2,5],
    [1,4]
])
np.linalg.det(X)

2.9999999999999996

In [ ]:
J = np.array([
    [7,3],
    [1,9]
])
np.linalg.det(J)

59.999999999999986

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
Y = np.array([
    [2,4,6,8],
    [4,3,2,1],
    [0,9,8,7],
    [3,4,5,6]
])
np.linalg.det(Y)

0.0

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
K = np.array([
    [3,9],
    [-2, 6]
])

np.array(K @ np.linalg.inv(K), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
F = np.array([
    [10,-5],
    [8, 6]
])
L= np.linalg.inv(K)
L

array([[ 0.16666667, -0.25      ],
       [ 0.05555556,  0.08333333]])

In [ ]:
L @ F

array([[-0.33333333, -2.33333333],
       [ 1.22222222,  0.22222222]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
J = np.array([
    [17,25,24,0,1,3,55],
    [9,44,0,1,2,3,4],
    [6,9,20,3,1,9,3],
    [2,6,4,4,9,33,1],
    [3,6,8,72,1,6,1],
    [-4,15,6,0,2,6,-30],
    [-22,-4,1,2,1,10,22],
])
J_inv = np.linalg.inv(J)
np.array(J @ J_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
squad = np.array([
    [2.0, 1.3, 6.5],
    [1.7, 0.1, 4.9],
    [4.3, 0.2, 2.0]
])
weights = np.array([
    [1.2, 2.2, 0.3]
])
p_grade = squad @ weights.T
p_grade


array([[7.21],
       [3.73],
       [6.2 ]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [2.0, 1.3, 6.5],
    [1.7, 0.1, 4.9],
    [4.3, 0.2, 2.0]
])
weights = np.array([
    [1.2, 2.2, 0.3]
])
p_grade = squad @ weights.T
p_grade


array([[7.21],
       [3.73],
       [6.2 ]])

## Activity


### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [3]:
A = np.array([
    [5, 4, 34],
    [3, 9, -5],
    [6, 10, 9]          
])

M = np.array([
    [1, 29, 6],
    [34, 4, 88],
    [9, -47, -22]          
])

P = np.array([
    [21, 90, -14],
    [14, -6, 9],
    [29, 1, 37]          
])

In [25]:
print ("First property states A*M is not equal to M*A")
print()

First property states A*M is not equal to M*A



In [4]:
A @ M

array([[  447, -1437,  -366],
       [  264,   358,   920],
       [  427,  -209,   718]])

In [5]:
A @ P

array([[1147,  460, 1224],
       [  44,  211, -146],
       [ 527,  489,  339]])

In [6]:
np.array_equiv(A @ M, M @ P)

False

In [27]:
print ("Second property states A@(M@P) = (A@M)@P)")
print ()

Second property states A@(M@P) = (A@M)@P)



In [7]:
A @ (M @ P)

array([[-21345,  48486, -32733],
       [ 37236,  22532,  33566],
       [ 26863,  40402,  18707]])

In [8]:
(A @ M) @ P

array([[-21345,  48486, -32733],
       [ 37236,  22532,  33566],
       [ 26863,  40402,  18707]])

In [9]:
np.array_equiv(A @( M @ P ),(A @ M)@P)

True

In [28]:
print ("Third property states A@(M+P) = (A@M)+(A@P)")
print()

Third property states A@(M+P) = (A@M)+(A@P)



In [10]:
A @(M + P)

array([[1594, -977,  858],
       [ 308,  569,  774],
       [ 954,  280, 1057]])

In [11]:
A @ M  + A @ P

array([[1594, -977,  858],
       [ 308,  569,  774],
       [ 954,  280, 1057]])

In [12]:
np.array_equiv(A@(M+P),A@M + A@P)

True

In [31]:
print ("Fourth property states (M+P)@A = M@A + P@A")
print()

Fourth property states (M+P)@A = M@A + P@A



In [13]:
(M + P) @ A

array([[ 419, 1079,   81],
       [ 816, 1144, 2515],
       [ 142, -112, 1657]])

In [14]:
M@A + P@A

array([[ 419, 1079,   81],
       [ 816, 1144, 2515],
       [ 142, -112, 1657]])

In [15]:
np.array_equiv((M+P)@A, M@A +P@A)

True

In [32]:
print ("Fifth property states A@I=A")
print()

Fifth property states A@I=A



In [16]:
A@np.eye(3)

array([[ 5.,  4., 34.],
       [ 3.,  9., -5.],
       [ 6., 10.,  9.]])

In [17]:
np.array_equiv(A, A@np.eye(3))

True

In [33]:
print ("Sixth property states A@0=0")
print()

Sixth property states A@0=0



In [18]:
A@np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.array_equiv(A@np.zeros((3,3)),np.zeros((3,3)))

True

In [20]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
z_mat = np.zeros (A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
i_dot_z = A.dot(np.zeros(A.shape))
i_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.array_equal(i_dot_z,z_mat)

True

In [24]:
null_mat = np.empty(A.shape, dtype = float)
null = np.array(null_mat,dtype = float)
print(null)
np.allclose(i_dot_z , null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Conclusion

Matrix operations, in general, play a vital role in our lives due to their applications, particularly in physics, engineering, and even healthcare. In fact, it's largely utilized in nutrition balancing to help people avoid consuming too much of something harmful to their health. Furthermore, with matrix operations, people can simply receive the exact amount of food they require.
The students learned about basic matrix operations and topics such as matrix transposition, dot product, determinant, and inverse after completing this laboratory assignment. They were also able to conduct these procedures in Python programming, which they may use to solve intermediate equations and engineering difficulties. The students were also able to demonstrate the six qualities of the dot product during this laboratory session. The students recognized that the qualities of the dot product are similar to the properties of multiplication in algebra after running the routines. However, unlike integers or variables in algebra, they differ in their commutative property because two matrices cannot be exchanged.

The operation of transposition involves swapping the rows and columns of a matrix. In some circumstances, the dot product is the same as the element-wise multiplication of matrices, but it must follow both rules. The first rule stipulates that two matrices must have the same inner dimensions in order to produce a dot product. The second rule, on the other hand, solely determines the attributes of the dot product. The determinant of a matrix, as well as its method for determining the inverse of a matrix, was then addressed. Finally, the students discovered that multiplying a given matrix by its inverse yields an identity matrix.
