<a href="https://colab.research.google.com/github/Marmalade17/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
## Laboratory 6 : Matrix Operations

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [9]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$


$$B = \begin{bmatrix} 5 & -1 & 2\\0 & -3 &2 \\ 1 & 3 & -9\end{bmatrix} $$


$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

In [19]:
X = np.array([
    [2 ,3, 6],
    [6, 0,1],
    [0, -3, 3]
])
X

array([[ 2,  3,  6],
       [ 6,  0,  1],
       [ 0, -3,  3]])

In [20]:
XT1 = np.transpose(A)


In [21]:
XT2 = X.T

In [22]:
np.array_equiv(XT1, XT2)

True

In [23]:
Y = np.array([
    [1,5,7,4],
    [2,0,2,0],
    [1,5,7,4],
    [2,0,2,0],
])
Y.shape

(4, 4)

In [24]:
np.transpose(Y).shape

(4, 4)

In [25]:
Y.T.shape

(4, 4)

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [45]:
L = np.array([
    [2,3],
    [-1,0]
])
M = np.array([
    [-2,-1, 0],
    [3,3, 3]
])

In [46]:
np.dot(L,M)

array([[5, 7, 9],
       [2, 1, 0]])

In [47]:
L.dot(M)

array([[5, 7, 9],
       [2, 1, 0]])

In [48]:
L @ M

array([[5, 7, 9],
       [2, 1, 0]])

In [49]:
np.matmul(L,M)

array([[5, 7, 9],
       [2, 1, 0]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [51]:
X = np.array([
    [3, 5],
    [4, -3],
    [1, 2]
])
Y = np.array([
    [2,2],
    [4,4],
    [-2,-3]
])
Z = np.array([
    [1,2,2],
    [0,0,3]
])
print(X.shape)
print(Y.shape)
print(Z.shape)

(3, 2)
(3, 2)
(2, 3)


In [52]:
X @ Z

array([[ 3,  6, 21],
       [ 4,  8, -1],
       [ 1,  2,  8]])

In [53]:
Y @ Z

array([[  2,   4,  10],
       [  4,   8,  20],
       [ -2,  -4, -13]])

In [54]:
X @ Y.T

array([[ 16,  32, -21],
       [  2,   4,   1],
       [  6,  12,  -8]])

In [64]:
L = np.array([
    [1,-2,4, 5],
    [2,-3,4,-5]
])
M = np.array([
    [0,-1,3, 4],
    [4,-2,5,-4]
])
print(L.shape)
print(M.shape)

(2, 4)
(2, 4)


In [65]:
M.T @ L

array([[  8, -12,  16, -20],
       [ -5,   8, -12,   5],
       [ 13, -21,  32, -10],
       [ -4,   4,   0,  40]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [66]:
X = np.array([
    [2,5],
    [1,4]
])
np.linalg.det(X)

2.9999999999999996

In [67]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
Y = np.array([
    [2,4,6,8],
    [4,3,2,1],
    [0,9,8,7],
    [3,4,5,6]
])
np.linalg.det(Y)

0.0

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [68]:
K = np.array([
    [3,9],
    [-2, 6]
])

np.array(K @ np.linalg.inv(K), dtype=int)

array([[1, 0],
       [0, 1]])

In [71]:
## And now let's test your skills in solving a matrix with high dimensions:
J = np.array([
    [17,25,24,0,1,3,55],
    [9,44,0,1,2,3,4],
    [6,9,20,3,1,9,3],
    [2,6,4,4,9,33,1],
    [3,6,8,72,1,6,1],
    [-4,15,6,0,2,6,-30],
    [-22,-4,1,2,1,10,22],
])
J_inv = np.linalg.inv(J)
np.array(J @ J_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [72]:
squad = np.array([
    [2.0, 1.3, 6.5],
    [1.7, 0.1, 4.9],
    [4.3, 0.2, 2.0]
])
weights = np.array([
    [1.2, 2.2, 0.3]
])
p_grade = squad @ weights.T
p_grade


array([[7.21],
       [3.73],
       [6.2 ]])

## Activity


### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

## Conclusion